[package]
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
description = "Events system"
edition = "2024"
homepage = "https://github.com/VladasZ/vents"
license = "MIT OR Apache-2.0"
name = "vents"
repository = "https://github.com/VladasZ/vents"
version = "0.15.0"

[features]
default = []

[dependencies]
hreads = "0.13"
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0"
gloo-timers = { version = "0.3", features = ["futures"] }
wasm-bindgen-futures = "0.4"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[build-dependencies]
plat = "0.8"
